name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: compilar o programa principal
        run: gcc fatorial.c function_fatorial.c -o fatorial

      - name: executar o programa principal
        run: ./fatorial 6

      - name: mostrar o conteudo do arquivo criado
        run: cat fatorial.txt

      - name: compilar o arquivo de teste
        run: gcc test_fatorial.c function_fatorial.c -o test_fatorial

      - name: executar o arquivo de teste
        run: ./test_fatorial
