      name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: compile
      run: gcc test_fatorial.c -o test_fatorial
    - name: execute
      run: ./test_fatorial
